server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
    main:
        allow-bean-definition-overriding: true
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.winter.model  # 注意：对应实体类的路径
    configuration:
        map-underscore-to-camel-case: true
